# Generated by Django 5.1.3 on 2024-12-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receipt_remaining_alter_receipt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveIntegerField(default=int),
            preserve_default=False,
        ),
    ]
