# Generated by Django 5.1.3 on 2024-12-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='semester_taken',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='year_level_taken',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
