# Generated by Django 5.1.3 on 2024-12-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_receipt_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted')], default='WAITLISTED', max_length=10),
            preserve_default=False,
        ),
    ]
