# Generated by Django 5.1.3 on 2025-01-08 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_acadtermbilling_created_at_acadtermbilling_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billinglist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
