# Generated by Django 5.1.3 on 2025-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_enrollment_date_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
