# Generated by Django 5.1.3 on 2025-01-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_receipt_paid_by_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
