# Generated by Django 5.1.3 on 2025-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_defaultcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('TRANSFEREE', 'Transferee')], default='REGULAR', max_length=15),
        ),
    ]
