# Generated by Django 5.1.3 on 2024-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_enrollment_semester_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
