# Generated by Django 5.1.3 on 2024-12-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_address_alter_student_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(db_comment='1.00 to 5.00 or S scale', max_length=4),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('TRANFEREE', 'Tranferee'), ('RETURNEE', 'Returnee'), ('NOT ENROLLED', 'Not Enrolled')], default='NOT ENROLLED', max_length=15),
        ),
    ]
