# Generated by Django 5.1.3 on 2024-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_student_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted'), ('NOT_ENROLLED', 'Not Enrolled')], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted'), ('NOT_ENROLLED', 'Not Enrolled')], default='NOT_ENROLLED', max_length=25),
        ),
    ]
