# Generated by Django 5.1.3 on 2025-01-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_program_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
