# Generated by Django 5.1.3 on 2025-01-08 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_program_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='enrollment_date',
        ),
        migrations.CreateModel(
            name='Enrollment_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_enrollment', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.program')),
            ],
            options={
                'db_table': 'enrollment_date',
            },
        ),
    ]
