# Generated by Django 5.1.3 on 2025-01-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_program_enrollment_date_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment_date',
            name='date',
            field=models.DateField(),
        ),
    ]
