# Generated by Django 5.1.3 on 2025-01-12 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_enrollment_date_is_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to='api.instructor'),
        ),
    ]
