# Generated by Django 5.1.3 on 2025-01-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_grade_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment_Date',
            new_name='EnrollmentDate',
        ),
    ]
